---
version: "3.7"
services:
  api:
    container_name: fibcraft_api
    image: fibcraft_api
    build: .
    ports:
      - "80:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
      
  minecraft-server:
    container_name: fibcraft_server
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./mc-paper:/data
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: LATEST
      MEMORY: 16G
    command: --noconsole
    image: itzg/minecraft-server
